### ISSUE TITLE
configure CI for pypi deployment

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#38]
configure travis or another CI (azure pipelines?) to build the package and deploy to pypi.

I think that Azure pipelines supports Windows, Mac, and Linux, which would make the maintenance of the CI much simpler than using both Travis and Appveyor. We could still do testing with Travis.

# TODO

- [x] working builds on Azure pipelines
- [ ] preserve artifacts
- [ ] trigger release on build from GitHub `develop` branch with tag containing v*.
- [ ] fix azure pipeline organization name from Andmoo22 to DeltaRCM

**Comment by amoodie** [comment]
I've got the tests running and package building on [Azure Pipelines](https://dev.azure.com/andmoo22/pyDeltaRCM), but I'm having a tough time figuring out how to correctly name the artifacts, and then access them in the "release" pipeline and upload to pypi.

**Comment by amoodie** [comment]
resolved with #63.
